version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=textmoderation
      - POSTGRES_PASSWORD=texmopassword123
      - POSTGRES_DB=textmoderationdb
    networks:
      - my_network

  backend:
    ports:
      - 3000:3000
    build: ./server
    volumes:
      - ./server/src:/app/src:delegated
    networks:
      - my_network

  frontend:
    ports:
      - 3001:3000
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src:delegated
      - ./frontend/public:/app/public:delegated
    networks:
      - my_network
    depends_on:
      - db
      - backend

networks:
  my_network: