on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: npm install
        run: npm install
        working-directory: ./server

      - name: Typecheck server
        run: npm run typecheck
        working-directory: ./server

      - name: Typecheck frontend
        run: npm run typecheck
        working-directory: ./frontend
