on: push
jobs:
  validate_frontend:
    name: validate frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: npm install frontend
        run: npm install
        working-directory: ./frontend

      - name: Typecheck frontend
        run: npm run typecheck
        working-directory: ./frontend

      - name: Eslint check
        run: npm run lint
        working-directory: ./frontend

      - name: Prettier frontend
        run: npm run prettier
        working-directory: ./frontend

  validate_backend:
    name: validate backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: npm install backend
        run: npm install
        working-directory: ./backend

      - name: Typecheck backend
        run: npm run typecheck
        working-directory: ./backend

      - name: Eslint check
        run: npm run lint
        working-directory: ./backend
        
      - name: Prettier backend
        run: npm run prettier
        working-directory: ./backend
